// server/config/constants.ts

export const ROLES = {
  ARTISAN: 'ARTISAN',
  BUYER: 'BUYER',
  COOPERATIVE: 'COOPERATIVE',
  REVIEWER: 'REVIEWER',
  ADMIN: 'ADMIN'
} as const;

export const PROVENANCE_EVENTS = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PASSPORT_CREATED: 'PASSPORT_CREATED',
  ARTISAN_VERIFIED: 'ARTISAN_VERIFIED',
  COOPERATIVE_VERIFIED: 'COOPERATIVE_VERIFIED',
  EVIDENCE_ADDED: 'EVIDENCE_ADDED',
  PRODUCT_VERIFIED: 'PRODUCT_VERIFIED',
  PRODUCT_SOLD: 'PRODUCT_SOLD',
  OWNERSHIP_TRANSFERRED: 'OWNERSHIP_TRANSFERRED',
  COUNTERFEIT_FLAGGED: 'COUNTERFEIT_FLAGGED',
  COUNTERFEIT_REVIEWED: 'COUNTERFEIT_REVIEWED',
  DISPUTE_CREATED: 'DISPUTE_CREATED',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED'
} as const;

export const GENESIS_PREVIOUS_HASH = '0000000000000000000000000000000000000000000000000000000000000000';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PROVENANCE_TAMPERED: 'PROVENANCE_TAMPERED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
} as const;

export const TRUST_WEIGHTS = {
  ARTISAN_VERIFICATION: 0.25,
  COOPERATIVE_AUDIT: 0.25,
  EVIDENCE_INTEGRITY: 0.25,
  PROVENANCE_HISTORY: 0.25
} as const;
